version: "3.8"
services:
  redis:
    image: redis
    command: redis-server /home/justuser/Cyber-resilience-of-artificial-intelligence-systems/redis.conf
    volumes:
      - /home/justuser/Cyber-resilience-of-artificial-intelligence-systems/redis.conf

  app:
    build:
      context: /home/justuser/Cyber-resilience-of-artificial-intelligence-systems/
    env_file:
      - /home/justuser/Cyber-resilience-of-artificial-intelligence-systems/.env
    restart: unless-stopped
    ports: 
      - 8000:8000
